In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
df=pd.read_csv("Student Depression Dataset.csv")

In [4]:
df.head()

,id,Gender,Age,City,Profession,Academic Pressure,Work Pressure,CGPA,Study Satisfaction,Job Satisfaction,Sleep Duration,Dietary Habits,Degree,Have you ever had suicidal thoughts ?,Work/Study Hours,Financial Stress,Family History of Mental Illness,Depression
0,2,Male,33.0,Visakhapatnam,Student,5.0,0.0,8.97,2.0,0.0,5-6 hours,Healthy,B.Pharm,Yes,3.0,1.0,No,1
1,8,Female,24.0,Bangalore,Student,2.0,0.0,5.90,5.0,0.0,5-6 hours,Moderate,BSc,No,3.0,2.0,Yes,0
2,26,Male,31.0,Srinagar,Student,3.0,0.0,7.03,5.0,0.0,Less than 5 hours,Healthy,BA,No,9.0,1.0,Yes,0
3,30,Female,28.0,Varanasi,Student,3.0,0.0,5.59,2.0,0.0,7-8 hours,Moderate,BCA,Yes,4.0,5.0,Yes,1
4,32,Female,25.0,Jaipur,Student,4.0,0.0,8.13,3.0,0.0,5-6 hours,Moderate,M.Tech,Yes,1.0,1.0,No,0

In [5]:
df.shape

(27901, 18)

In [8]:
df[df["City"]=="Bangalore"].shape

(767, 18)

In [10]:
df.query('City=="Jaipur"')

,id,Gender,Age,City,Profession,Academic Pressure,Work Pressure,CGPA,Study Satisfaction,Job Satisfaction,Sleep Duration,Dietary Habits,Degree,Have you ever had suicidal thoughts ?,Work/Study Hours,Financial Stress,Family History of Mental Illness,Depression
4,32,Female,25.0,Jaipur,Student,4.0,0.0,8.13,3.0,0.0,5-6 hours,Moderate,M.Tech,Yes,1.0,1.0,No,0
32,239,Male,21.0,Jaipur,Student,1.0,0.0,7.25,1.0,0.0,Less than 5 hours,Healthy,MCA,Yes,7.0,2.0,No,0
60,348,Male,25.0,Jaipur,Student,5.0,0.0,9.21,1.0,0.0,5-6 hours,Unhealthy,BSc,No,7.0,3.0,Yes,0
108,592,Male,27.0,Jaipur,Student,2.0,0.0,8.79,1.0,0.0,5-6 hours,Unhealthy,MCA,Yes,8.0,4.0,No,1
127,681,Male,26.0,Jaipur,Student,3.0,0.0,5.14,3.0,0.0,7-8 hours,Healthy,MSc,No,12.0,1.0,No,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27754,139879,Male,22.0,Jaipur,Student,2.0,0.0,6.52,4.0,0.0,Less than 5 hours,Moderate,B.Ed,Yes,9.0,2.0,No,1
27784,140024,Male,29.0,Jaipur,Student,1.0,0.0,5.69,5.0,0.0,More than 8 hours,Unhealthy,MCA,Yes,4.0,5.0,Yes,1
27835,140312,Female,24.0,Jaipur,Student,3.0,0.0,7.22,1.0,0.0,More than 8 hours,Unhealthy,BSc,Yes,2.0,2.0,Yes,1
27872,140518,Male,34.0,Jaipur,Student,4.0,0.0,5.12,5.0,0.0,7-8 hours,Healthy,MD,Yes,4.0,4.0,Yes,0
27886,140601,Female,22.0,Jaipur,Student,5.0,0.0,9.25,4.0,0.0,More than 8 hours,Unhealthy,BBA,Yes,8.0,3.0,No,1

In [15]:
df.query('City=="Bangalore" &  Age<30')

,id,Gender,Age,City,Profession,Academic Pressure,Work Pressure,CGPA,Study Satisfaction,Job Satisfaction,Sleep Duration,Dietary Habits,Degree,Have you ever had suicidal thoughts ?,Work/Study Hours,Financial Stress,Family History of Mental Illness,Depression
1,8,Female,24.0,Bangalore,Student,2.0,0.0,5.90,5.0,0.0,5-6 hours,Moderate,BSc,No,3.0,2.0,Yes,0
24,173,Male,18.0,Bangalore,Student,4.0,0.0,7.10,3.0,0.0,More than 8 hours,Unhealthy,Class 12,Yes,11.0,5.0,Yes,1
117,623,Female,23.0,Bangalore,Student,5.0,0.0,5.66,1.0,0.0,Less than 5 hours,Unhealthy,MCA,Yes,11.0,4.0,No,1
160,779,Male,20.0,Bangalore,Student,5.0,0.0,9.72,1.0,0.0,5-6 hours,Healthy,Class 12,Yes,11.0,2.0,No,1
202,984,Male,22.0,Bangalore,Student,1.0,0.0,7.25,5.0,0.0,7-8 hours,Unhealthy,BE,Yes,9.0,5.0,Yes,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27196,137131,Male,27.0,Bangalore,Student,1.0,0.0,8.64,1.0,0.0,7-8 hours,Moderate,B.Pharm,No,3.0,4.0,No,0
27253,137412,Female,28.0,Bangalore,Student,2.0,0.0,9.47,1.0,0.0,5-6 hours,Moderate,BCA,Yes,7.0,5.0,No,1
27286,137603,Male,20.0,Bangalore,Student,4.0,0.0,8.24,4.0,0.0,More than 8 hours,Healthy,Class 12,Yes,7.0,5.0,Yes,1
27290,137629,Female,20.0,Bangalore,Student,4.0,0.0,7.94,5.0,0.0,Less than 5 hours,Unhealthy,Class 12,Yes,12.0,2.0,Yes,1
27318,137764,Male,22.0,Bangalore,Student,5.0,0.0,9.39,1.0,0.0,Less than 5 hours,Healthy,Class 12,Yes,9.0,5.0,Yes,1

In [19]:
df.groupby("Degree")["Work/Study Hours","CGPA","Financial Stress"].mean()

<ipython-input-19-1fdf9b95983b>:1: FutureWarning: Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.
  df.groupby("Degree")["Work/Study Hours","CGPA","Financial Stress"].mean()

          Work/Study Hours      CGPA  Financial Stress
Degree
B.Arch            7.266576  7.616502          3.172530
B.Com             7.227756  7.671826          3.115538
B.Ed              7.164971  7.850911          3.078242
B.Pharm           6.708642  7.707753          3.103704
B.Tech            7.070312  7.636513          3.050347
BA                7.195000  7.761300          2.988333
BBA               7.031609  7.714468          3.206897
BCA               7.226797  7.769281          3.114525
BE                7.161501  7.484617          3.143556
BHM               7.069189  7.649859          3.060541
BSc               7.248874  7.576824          3.127252
Class 12          7.278289  7.594184          3.279276
LLB               7.226528  7.686602          3.110283
LLM               6.927386  7.879419          2.966805
M.Com             6.828338  7.788978          3.110354
M.Ed              7.021924  7.707491          3.002436
M.Pharm           7.049828  7.513574          3.135739
M.Tech            7.393346  7.592896          3.078278
MA                7.380515  8.028364          3.053309
MBA               7.357651  7.679431          3.040925
MBBS              7.051724  7.551767          3.256115
MCA               7.022031  7.562854          3.092912
MD                6.973776  7.691381          2.986014
ME                6.989189  7.269676          3.064865
MHM               7.178010  7.606440          3.089005
MSc               7.168908  7.513261          3.178151
Others            5.857143  7.588857          3.371429
PhD               6.741379  7.677088          3.107280

In [21]:
df.groupby("Degree")["Work/Study Hours","CGPA","Financial Stress"].mean().head(5)

<ipython-input-21-a6d266a07a62>:1: FutureWarning: Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.
  df.groupby("Degree")["Work/Study Hours","CGPA","Financial Stress"].mean().head(5)

         Work/Study Hours      CGPA  Financial Stress
Degree
B.Arch           7.266576  7.616502          3.172530
B.Com            7.227756  7.671826          3.115538
B.Ed             7.164971  7.850911          3.078242
B.Pharm          6.708642  7.707753          3.103704
B.Tech           7.070312  7.636513          3.050347

In [22]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 27901 entries, 0 to 27900
Data columns (total 18 columns):
 #   Column                                 Non-Null Count  Dtype
---  ------                                 --------------  -----
 0   id                                     27901 non-null  int64
 1   Gender                                 27901 non-null  object
 2   Age                                    27901 non-null  float64
 3   City                                   27901 non-null  object
 4   Profession                             27901 non-null  object
 5   Academic Pressure                      27901 non-null  float64
 6   Work Pressure                          27901 non-null  float64
 7   CGPA                                   27901 non-null  float64
 8   Study Satisfaction                     27901 non-null  float64
 9   Job Satisfaction                       27901 non-null  float64
 10  Sleep Duration                         27901 non-null  object
 11  Dietary Habits                         27901 non-null  object
 12  Degree                                 27901 non-null  object
 13  Have you ever had suicidal thoughts ?  27901 non-null  object
 14  Work/Study Hours                       27901 non-null  float64
 15  Financial Stress                       27898 non-null  float64
 16  Family History of Mental Illness       27901 non-null  object
 17  Depression                             27901 non-null  int64
dtypes: float64(8), int64(2), object(8)
memory usage: 3.8+ MB

In [33]:
df["CGPA"].value_counts().head(10)

8.04    821
9.96    425
5.74    410
8.95    371
9.21    343
7.25    339
7.09    320
7.88    318
9.44    317
8.91    276
Name: CGPA, dtype: int64